# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Yacoub Kureh
description:      'Hi Welcome to my second page'
url:              http://www.math.ucla.edu/~ykureh/
baseurl:          ""

# Options: 7, 8, 9, a, b, c, d, e, f
theme_id: "7"

author:
  name:           'Yacoub Kureh'
  url:            http://www.math.ucla.edu/~ykureh/

# Blog configuration
has_blog:         False
paginate:         1
paginate_path:    "/blog/page:num/"
blog_url:        "/blog/"

# Configure prose
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
